seed: 42

paths:
  raw_csv: data/raw/Fraud.csv
  model_path: models/fraud_xgb.pkl

training:
  algorithm: xgboost
  params:
    n_estimators: 300
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    tree_method: hist
    n_jobs: -1
  imbalance:
    use_scale_pos_weight: true

inference:
  threshold: 0.80

api:
  url: http://localhost:8000
